"""add external ids to albums

Revision ID: 5a1cf29f69c9
Revises: 918bf2ccad18
Create Date: 2026-05-21 16:28:43.878642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1cf29f69c9'
down_revision: Union[str, Sequence[str], None] = '918bf2ccad18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('musicbrainz_id', sa.String(length=100), nullable=True))
    op.add_column('albums', sa.Column('discogs_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'albums', ['discogs_id'])
    op.create_unique_constraint(None, 'albums', ['musicbrainz_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='unique')
    op.drop_constraint(None, 'albums', type_='unique')
    op.drop_column('albums', 'discogs_id')
    op.drop_column('albums', 'musicbrainz_id')
    # ### end Alembic commands ###
