"""add album image url

Revision ID: 918bf2ccad18
Revises: 5d85f0354354
Create Date: 2026-05-21 16:19:45.556369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918bf2ccad18'
down_revision: Union[str, Sequence[str], None] = '5d85f0354354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'image_url')
    # ### end Alembic commands ###
