"""add locations

Revision ID: c59bf641477c
Revises: f993931ced73
Create Date: 2026-05-20 23:01:45.623715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59bf641477c'
down_revision: Union[str, Sequence[str], None] = 'f993931ced73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('collection_items', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection_items', 'locations', ['location_id'], ['id'])
    op.drop_column('collection_items', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collection_items', type_='foreignkey')
    op.drop_column('collection_items', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
